# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('case_id', models.CharField(max_length=20)),
                ('plaintiff', models.CharField(max_length=50)),
                ('defendant', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document_template',
            fields=[
                ('id_document_template', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('template', models.FileField(upload_to='document_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id_mail', models.AutoField(primary_key=True, serialize=False)),
                ('date_send', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.TextField(default='')),
                ('id_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='electroniccourt.Document')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='id_reciever',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='electroniccourt.User'),
        ),
        migrations.AddField(
            model_name='mail',
            name='id_sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='electroniccourt.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electroniccourt.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_document_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electroniccourt.Document_template'),
        ),
    ]
