# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('electroniccourt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electroniccourt.User')),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='id_creator',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='id_document_template',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='id_document',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='id_reciever',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='id_sender',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='date_send',
            new_name='sending_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='feedback',
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electroniccourt.Mail'),
        ),
    ]
