# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroniccourt', '0002_auto_20171209_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='state',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
