# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electroniccourt', '0003_document_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id_permission', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permission', models.ManyToManyField(related_name='permission', to='electroniccourt.Permission')),
                ('id_user', models.ManyToManyField(related_name='user', to='electroniccourt.User')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='electroniccourt.User'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='electroniccourt.Mail'),
        ),
    ]
