# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electroniccourt', '0004_auto_20171209_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electroniccourt.User'),
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electroniccourt.Document_template'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='electroniccourt.User'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='electroniccourt.Mail'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='electroniccourt.Document'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='electroniccourt.User'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='electroniccourt.User'),
        ),
    ]
